# Generated by Django 4.2 on 2025-05-13 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0002_organizationprofile"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="organizationprofile",
            name="document",
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="document_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="document_url",
            field=models.URLField(blank=True),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="address",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="org_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="organizationprofile",
            name="phone_number",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
