# Generated by Django 4.2 on 2025-05-27 21:23

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0003_remove_organizationprofile_document_and_more"),
    ]

    operations = [
        migrations.DeleteModel(
            name="OrganizationProfile",
        ),
    ]
