# Generated by Django 4.2 on 2025-07-15 10:28

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0004_delete_organizationprofile"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="phone_number",
            field=models.CharField(blank=True, max_length=8, null=True),
        ),
    ]
