# Generated by Django 4.2 on 2025-08-13 16:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0006_user_is_platform_admin_alter_user_role"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="supabase_id",
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
    ]
