# Generated by Django 4.2 on 2025-08-13 16:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("accounts", "0007_user_supabase_id"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="supabase_id",
            field=models.CharField(max_length=100),
        ),
    ]
