# Generated by Django 4.2 on 2025-05-19 10:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0002_category_campaign_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="category",
            field=models.ForeignKey(
                default=2,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="campaign.category",
            ),
            preserve_default=False,
        ),
    ]
