# Generated by Django 4.2 on 2025-05-20 12:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0003_alter_campaign_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="featured",
            field=models.BooleanField(default=False),
        ),
    ]
