# Generated by Django 4.2 on 2025-06-26 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0005_donation_donationwebhooklog_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="facebook_access_token",
            field=models.TextField(
                blank=True, help_text="Facebook access token for API calls", null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="facebook_live_url",
            field=models.URLField(
                blank=True, help_text="Facebook Live stream URL", null=True
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="facebook_video_id",
            field=models.CharField(
                blank=True,
                help_text="Extracted Facebook video ID",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="live_status",
            field=models.CharField(
                choices=[
                    ("none", "No Live Stream"),
                    ("live", "Currently Live"),
                    ("ended", "Stream Ended"),
                ],
                default="none",
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name="campaign",
            name="live_viewer_count",
            field=models.IntegerField(default=0, help_text="Current live viewer count"),
        ),
    ]
