# Generated by Django 4.2 on 2025-08-19 13:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("campaign", "0007_alter_campaign_owner"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="donationwebhooklog",
            name="donation",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="currency",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="donor_email",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="external_transaction_id",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="payment_metadata",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="donation",
            name="payment_transaction_id",
        ),
        migrations.AlterField(
            model_name="donation",
            name="donor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="donations",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["status", "created_at"], name="campaign_do_status_66f709_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="donation",
            index=models.Index(
                fields=["donor", "created_at"], name="campaign_do_donor_i_d08255_idx"
            ),
        ),
        migrations.DeleteModel(
            name="DonationWebhookLog",
        ),
    ]
