# Generated by Django 4.2 on 2025-08-20 11:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0009_alter_manualpayment_unique_together_and_more"),
        ("campaign", "0008_remove_donationwebhooklog_donation_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="organization",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="campaigns",
                to="organizations.organizationprofile",
            ),
        ),
    ]
