# Generated by Django 4.2 on 2025-10-06 16:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0010_category_icon_class"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["owner", "-created_at"], name="campaign_ca_owner_i_35a050_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["current_amount"], name="campaign_ca_current_2dc13e_idx"
            ),
        ),
    ]
