# Generated by Django 4.2 on 2025-10-07 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0011_campaign_campaign_ca_owner_i_35a050_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["category", "-created_at"],
                name="campaign_ca_categor_4a89ed_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["featured", "-created_at"],
                name="campaign_ca_feature_a2f3a6_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["live_status"], name="campaign_ca_live_st_157380_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["organization", "-created_at"],
                name="campaign_ca_organiz_842156_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(
                fields=["current_amount", "target", "-created_at"],
                name="campaign_ca_current_c7ee62_idx",
            ),
        ),
    ]
