# Generated by Django 4.2 on 2025-10-07 10:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0012_campaign_campaign_ca_categor_4a89ed_idx_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="campaign",
            index=models.Index(fields=["name"], name="campaign_ca_name_845ec8_idx"),
        ),
    ]
