# Generated by Django 4.2 on 2025-06-04 12:30

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0002_walletprovider_organizationpaymentnumber"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationpaymentnumber",
            old_name="is_active",
            new_name="is_primary",
        ),
    ]
