# Generated by Django 4.2 on 2025-06-04 12:34

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0003_rename_is_active_organizationpaymentnumber_is_primary"),
    ]

    operations = [
        migrations.RenameField(
            model_name="organizationpaymentnumber",
            old_name="is_primary",
            new_name="is_active",
        ),
    ]
