# Generated by Django 4.2 on 2025-06-19 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0004_rename_is_primary_organizationpaymentnumber_is_active"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_payment",
                        to="organizations.organizationprofile",
                    ),
                ),
                (
                    "wallet_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.walletprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("organization", "wallet_provider", "phone_number")
                },
            },
        ),
        migrations.CreateModel(
            name="NextPayPayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("commercial_number", models.CharField(max_length=20)),
                ("account_name", models.CharField(blank=True, max_length=100)),
                ("is_active", models.BooleanField(default=True)),
                ("verified_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="nextpay_payments",
                        to="organizations.organizationprofile",
                    ),
                ),
                (
                    "wallet_provider",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="organizations.walletprovider",
                    ),
                ),
            ],
            options={
                "unique_together": {
                    ("organization", "wallet_provider", "commercial_number")
                },
            },
        ),
        migrations.DeleteModel(
            name="OrganizationPaymentNumber",
        ),
    ]
