# Generated by Django 4.2 on 2025-06-19 13:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0006_alter_manualpayment_organization"),
    ]

    operations = [
        migrations.AlterField(
            model_name="manualpayment",
            name="organization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="manual_payments",
                to="organizations.organizationprofile",
            ),
        ),
    ]
