# Generated by Django 4.2 on 2025-08-04 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0007_alter_manualpayment_organization"),
    ]

    operations = [
        migrations.AddField(
            model_name="organizationprofile",
            name="cover_image_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="cover_image_url",
            field=models.URLField(blank=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="profile_image_path",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="profile_image_url",
            field=models.URLField(blank=True),
        ),
    ]
