# Generated by Django 4.2 on 2025-08-19 13:20

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("organizations", "0008_organizationprofile_cover_image_path_and_more"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="manualpayment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="manualpayment",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="manualpayment",
            name="wallet_provider",
        ),
        migrations.AlterUniqueTogether(
            name="nextpaypayment",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="nextpaypayment",
            name="organization",
        ),
        migrations.RemoveField(
            model_name="nextpaypayment",
            name="wallet_provider",
        ),
        migrations.AlterModelOptions(
            name="organizationprofile",
            options={"ordering": ["org_name"]},
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="city",
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="country",
            field=models.CharField(default="Mauritania", max_length=100),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="nextremitly_api_key",
            field=models.CharField(
                blank=True,
                help_text="NextRemitly API key for receiving payments",
                max_length=500,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="organizationprofile",
            name="payment_enabled",
            field=models.BooleanField(
                default=False,
                help_text="Enable payment processing for this organization",
            ),
        ),
        migrations.AddIndex(
            model_name="organizationprofile",
            index=models.Index(
                fields=["is_verified"], name="organizatio_is_veri_ea5640_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="organizationprofile",
            index=models.Index(
                fields=["payment_enabled"], name="organizatio_payment_5af5b2_idx"
            ),
        ),
        migrations.DeleteModel(
            name="ManualPayment",
        ),
        migrations.DeleteModel(
            name="NextPayPayment",
        ),
        migrations.DeleteModel(
            name="WalletProvider",
        ),
    ]
