# Generated by Django 4.2 on 2025-07-03 10:55

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("phone", models.CharField(max_length=20)),
                (
                    "available_locations",
                    models.TextField(
                        help_text="JSON string of selected locations from frontend"
                    ),
                ),
                (
                    "age",
                    models.IntegerField(
                        validators=[
                            django.core.validators.MinValueValidator(16),
                            django.core.validators.MaxValueValidator(100),
                        ]
                    ),
                ),
                ("profession", models.CharField(blank=True, max_length=100)),
                ("motivation", models.TextField()),
                ("skills", models.TextField(help_text="Comma-separated skills")),
                ("interests", models.TextField(help_text="Comma-separated interests")),
                ("languages", models.TextField(help_text="Comma-separated languages")),
                (
                    "availability",
                    models.TextField(
                        help_text="JSON string of availability data from frontend"
                    ),
                ),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_profile",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_profiles",
            },
        ),
    ]
