# Generated by Django 4.2 on 2025-07-23 12:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("campaign", "0006_campaign_facebook_access_token_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("volunteers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="VolunteerInvitation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("pending", "Pending"),
                            ("accepted", "Accepted"),
                            ("declined", "Declined"),
                            ("expired", "Expired"),
                        ],
                        default="pending",
                        max_length=20,
                    ),
                ),
                (
                    "match_score",
                    models.FloatField(default=0.0, help_text="Matching score (0-100)"),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, help_text="Personal message to volunteer"
                    ),
                ),
                (
                    "response_message",
                    models.TextField(
                        blank=True, help_text="Volunteer's response message"
                    ),
                ),
                ("invited_at", models.DateTimeField(auto_now_add=True)),
                ("responded_at", models.DateTimeField(blank=True, null=True)),
                ("expires_at", models.DateTimeField(blank=True, null=True)),
            ],
            options={
                "db_table": "volunteer_invitations",
                "ordering": ["-invited_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerRequest",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("description", models.TextField()),
                (
                    "required_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated must-have skills"
                    ),
                ),
                (
                    "required_locations",
                    models.TextField(
                        blank=True, help_text="JSON string of required locations"
                    ),
                ),
                ("min_age", models.IntegerField(blank=True, null=True)),
                ("max_age", models.IntegerField(blank=True, null=True)),
                (
                    "required_languages",
                    models.TextField(
                        blank=True, help_text="Comma-separated required languages"
                    ),
                ),
                (
                    "preferred_skills",
                    models.TextField(
                        blank=True, help_text="Comma-separated preferred skills"
                    ),
                ),
                (
                    "preferred_locations",
                    models.TextField(
                        blank=True, help_text="JSON string of preferred locations"
                    ),
                ),
                (
                    "preferred_languages",
                    models.TextField(
                        blank=True, help_text="Comma-separated preferred languages"
                    ),
                ),
                (
                    "preferred_interests",
                    models.TextField(
                        blank=True, help_text="Comma-separated preferred interests"
                    ),
                ),
                ("event_date", models.DateTimeField()),
                ("event_end_date", models.DateTimeField(blank=True, null=True)),
                ("duration_hours", models.IntegerField()),
                ("volunteers_needed", models.IntegerField()),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("low", "Low"),
                            ("medium", "Medium"),
                            ("high", "High"),
                            ("urgent", "Urgent"),
                        ],
                        default="medium",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("open", "Open"),
                            ("in_progress", "In Progress"),
                            ("completed", "Completed"),
                            ("cancelled", "Cancelled"),
                        ],
                        default="open",
                        max_length=20,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "special_requirements",
                    models.TextField(
                        blank=True, help_text="Any special requirements or notes"
                    ),
                ),
                (
                    "campaign",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_requests",
                        to="campaign.campaign",
                    ),
                ),
                (
                    "organization",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="volunteer_requests",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_requests",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="VolunteerNotification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "notification_type",
                    models.CharField(
                        choices=[
                            ("invitation", "New Invitation"),
                            ("invitation_update", "Invitation Update"),
                            ("request_update", "Request Update"),
                            ("general", "General"),
                        ],
                        max_length=20,
                    ),
                ),
                ("title", models.CharField(max_length=200)),
                ("message", models.TextField()),
                ("is_read", models.BooleanField(default=False)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "invitation",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteers.volunteerinvitation",
                    ),
                ),
                (
                    "request",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="volunteers.volunteerrequest",
                    ),
                ),
                (
                    "volunteer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to="volunteers.volunteerprofile",
                    ),
                ),
            ],
            options={
                "db_table": "volunteer_notifications",
                "ordering": ["-created_at"],
            },
        ),
        migrations.AddField(
            model_name="volunteerinvitation",
            name="request",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="volunteers.volunteerrequest",
            ),
        ),
        migrations.AddField(
            model_name="volunteerinvitation",
            name="volunteer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="invitations",
                to="volunteers.volunteerprofile",
            ),
        ),
        migrations.AlterUniqueTogether(
            name="volunteerinvitation",
            unique_together={("request", "volunteer")},
        ),
    ]
